before_script:
    - apt-get update -qy
    - apt-get install -qy libssl-dev build-essential wget
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
    - source /root/.bashrc
    - nvm install node
    - nvm use node
    - npm install && npm install -g mocha

test:
    script:
        - npm test
