sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
  - lts/*
before_script:
  - npm prune
  - npm install codecov
script:
  - npm test
after_success:
  - codecov
  - npm run semantic-release
