sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 7
  - 6
  - 5
  - 4
  - '0.12'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run test
  - npm run check-coverage
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
