sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 7
  - 6
  - 5
  - 4
  - '0.12'
before_script:
  - npm prune
script:
  - npm test
  - npm run check-coverage
after_success:
  - npm run semantic-release
