sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
  - lts/*
before_script:
  - npm install codecov
script:
  - npm test
after_success:
  - codecov
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
