name: Node CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x (LTS)
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: npm build and test
      run: |
        npm run build --if-present
        npm test
